@KindRaise.Api_HostAddress = http://localhost:5138

POST {{KindRaise.Api_HostAddress}}/api/campaigns
Content-Type: application/json

{
  "title": "Help Build a School",
  "description": "A campaign to raise money for a new school.",
  "monetaryGoal": 10000,
  "startDate": "2026-09-18T00:00:00Z",
  "endDate": "2026-09-19T23:59:59Z"
}


###
