@KindRaise.Api_HostAddress = http://localhost:5138

POST {{KindRaise.Api_HostAddress}}/api/campaigns
Content-Type: application/json

{
  "name": "Help Build a School",
  "description": "A campaign to raise money for a new school.",
  "monetaryGoal": 10000
}


###
